<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Alert
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'eCode',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'eMsgEn',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $eCode = null;
    /**
     * @var string
     */
    public $eMsgEn = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['eCode'])) {
                $this->eCode = $vals['eCode'];
            }
            if (isset($vals['eMsgEn'])) {
                $this->eMsgEn = $vals['eMsgEn'];
            }
        }
    }

    public function getName()
    {
        return 'Alert';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->eCode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->eMsgEn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Alert');
        if ($this->eCode !== null) {
            $xfer += $output->writeFieldBegin('eCode', TType::STRING, 1);
            $xfer += $output->writeString($this->eCode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->eMsgEn !== null) {
            $xfer += $output->writeFieldBegin('eMsgEn', TType::STRING, 2);
            $xfer += $output->writeString($this->eMsgEn);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
