<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class Constant extends \Thrift\Type\TConstant
{
    static protected $ApiVersion;
    static protected $PrintableAsciiRe;
    static protected $IdentMatchRe;
    static protected $ApiErrors;

    protected static function init_ApiVersion()
    {
        return "1.1";
    }

    protected static function init_PrintableAsciiRe()
    {
        return "^[\\x20-\\x7e]*\$";
    }

    protected static function init_IdentMatchRe()
    {
        return "^[a-zA-Z0-9][a-zA-Z0-9_\\-\\.,]{0,39}\$";
    }

    protected static function init_ApiErrors()
    {
        return array(
            "EAuthentication.Permission" => "Access denied: accessToken does not have permission '{0}'",
            "EAuthentication.Token" => "Authentication failed (bad accessToken: {0})",
            "ECacheMiss" => "The requested entry was not found in the cache",
            "EKeystore.NotFound" => "Vending Key not available for SGC={0},KRN={1} (reason: {2})",
            "EParamRange" => "Parameter '{0}' out of range: got '{1}', expected {2}",
            "EPrefRange" => "Preference '{0}' out of range: got '{1}', expected {2}",
            "EService" => "Unhandled exception '{0}': {1}",
            "EService.Disabled" => "Feature disabled: {0}",
            "ESignin.Authentication" => "Sign-in failed: authentication failed for realm='{0}' username='{1}'",
            "ESignin.Permission" => "Sign-in failed: realm='{0}' username='{1}' does not have permission '{2}'",
            "ESignin.Realm" => "Sign-in failed: unknown realm='{0}'",
            "ESignin.Subject" => "Sign-in failed: unknown username='{1}' in realm='{0}'",
            "ESignin.Version" => "This service (API version={0}) does not support your client's API version='{1}'",
            "ESm" => "Security Module error '{0}': {1}",
            "ESts.DrnOrPan" => "Parameter '{0}' is an invalid meter DRN/PAN (reason: {2}); got '{1}'",
            "ESts.DrnOrPan.CheckDigit" => "Parameter '{0}' is a meter DRN/PAN with bad check digit(s); got '{1}'",
            "ESts.IdRecord" => "Parameter '{0}' is an invalid IDRecord/Record2 (reason: {2}); got '{1}'",
            "ESts.IdRecord.Expired" => "Meter identification has expired (YYMM='{0}')",
            "ESts.VkBeforeBdt" => "Attempt to use Vending Key before its Base Date",
            "ESts.VkExpired" => "Vending Key has expired (TokenID exceeds KeyExpiryNumber)",
            "EVerify.Crc" => "Invalid token: CRC error",
            "EVerify.DdtkCredit" => "Invalid token: Class 0 token encrypted under a DDTK",
            "EVerify.KeyExpired" => "Invalid token: TokenID out of range for Vending Key KeyExpiryNumber",
            "EVerify.Ok" => "(Not an error) Token is valid",
        );
    }
}
