<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MeterConfigAdvice
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'toSgc',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'toKrn',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        3 => array(
            'var' => 'toTi',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        4 => array(
            'var' => 'toKen',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        10 => array(
            'var' => 'idRecord',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        11 => array(
            'var' => 'record2',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        20 => array(
            'var' => 'rollover',
            'isRequired' => true,
            'type' => TType::BOOL,
        ),
        21 => array(
            'var' => 'toVkKcv',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $toSgc = null;
    /**
     * @var int
     */
    public $toKrn = null;
    /**
     * @var int
     */
    public $toTi = null;
    /**
     * @var int
     */
    public $toKen = null;
    /**
     * @var string
     */
    public $idRecord = null;
    /**
     * @var string
     */
    public $record2 = null;
    /**
     * @var bool
     */
    public $rollover = null;
    /**
     * @var string
     */
    public $toVkKcv = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['toSgc'])) {
                $this->toSgc = $vals['toSgc'];
            }
            if (isset($vals['toKrn'])) {
                $this->toKrn = $vals['toKrn'];
            }
            if (isset($vals['toTi'])) {
                $this->toTi = $vals['toTi'];
            }
            if (isset($vals['toKen'])) {
                $this->toKen = $vals['toKen'];
            }
            if (isset($vals['idRecord'])) {
                $this->idRecord = $vals['idRecord'];
            }
            if (isset($vals['record2'])) {
                $this->record2 = $vals['record2'];
            }
            if (isset($vals['rollover'])) {
                $this->rollover = $vals['rollover'];
            }
            if (isset($vals['toVkKcv'])) {
                $this->toVkKcv = $vals['toVkKcv'];
            }
        }
    }

    public function getName()
    {
        return 'MeterConfigAdvice';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->toSgc);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->toKrn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->toTi);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->toKen);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->idRecord);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->record2);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 20:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->rollover);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 21:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->toVkKcv);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MeterConfigAdvice');
        if ($this->toSgc !== null) {
            $xfer += $output->writeFieldBegin('toSgc', TType::I32, 1);
            $xfer += $output->writeI32($this->toSgc);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toKrn !== null) {
            $xfer += $output->writeFieldBegin('toKrn', TType::I16, 2);
            $xfer += $output->writeI16($this->toKrn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toTi !== null) {
            $xfer += $output->writeFieldBegin('toTi', TType::I16, 3);
            $xfer += $output->writeI16($this->toTi);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toKen !== null) {
            $xfer += $output->writeFieldBegin('toKen', TType::I16, 4);
            $xfer += $output->writeI16($this->toKen);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->idRecord !== null) {
            $xfer += $output->writeFieldBegin('idRecord', TType::STRING, 10);
            $xfer += $output->writeString($this->idRecord);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->record2 !== null) {
            $xfer += $output->writeFieldBegin('record2', TType::STRING, 11);
            $xfer += $output->writeString($this->record2);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->rollover !== null) {
            $xfer += $output->writeFieldBegin('rollover', TType::BOOL, 20);
            $xfer += $output->writeBool($this->rollover);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toVkKcv !== null) {
            $xfer += $output->writeFieldBegin('toVkKcv', TType::STRING, 21);
            $xfer += $output->writeString($this->toVkKcv);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
