<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MeterTestToken
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'drn',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'pan',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        10 => array(
            'var' => 'tokenClass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        11 => array(
            'var' => 'subclass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        12 => array(
            'var' => 'control',
            'isRequired' => true,
            'type' => TType::I64,
        ),
        13 => array(
            'var' => 'mfrcode',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        20 => array(
            'var' => 'description',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        30 => array(
            'var' => 'tokenDec',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        31 => array(
            'var' => 'tokenHex',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $drn = null;
    /**
     * @var string
     */
    public $pan = null;
    /**
     * @var int
     */
    public $tokenClass = null;
    /**
     * @var int
     */
    public $subclass = null;
    /**
     * @var int
     */
    public $control = null;
    /**
     * @var int
     */
    public $mfrcode = null;
    /**
     * @var string
     */
    public $description = null;
    /**
     * @var string
     */
    public $tokenDec = null;
    /**
     * @var string
     */
    public $tokenHex = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['drn'])) {
                $this->drn = $vals['drn'];
            }
            if (isset($vals['pan'])) {
                $this->pan = $vals['pan'];
            }
            if (isset($vals['tokenClass'])) {
                $this->tokenClass = $vals['tokenClass'];
            }
            if (isset($vals['subclass'])) {
                $this->subclass = $vals['subclass'];
            }
            if (isset($vals['control'])) {
                $this->control = $vals['control'];
            }
            if (isset($vals['mfrcode'])) {
                $this->mfrcode = $vals['mfrcode'];
            }
            if (isset($vals['description'])) {
                $this->description = $vals['description'];
            }
            if (isset($vals['tokenDec'])) {
                $this->tokenDec = $vals['tokenDec'];
            }
            if (isset($vals['tokenHex'])) {
                $this->tokenHex = $vals['tokenHex'];
            }
        }
    }

    public function getName()
    {
        return 'MeterTestToken';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->drn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->pan);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->tokenClass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->subclass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->control);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->mfrcode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 20:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->description);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 30:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tokenDec);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 31:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tokenHex);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MeterTestToken');
        if ($this->drn !== null) {
            $xfer += $output->writeFieldBegin('drn', TType::STRING, 1);
            $xfer += $output->writeString($this->drn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->pan !== null) {
            $xfer += $output->writeFieldBegin('pan', TType::STRING, 2);
            $xfer += $output->writeString($this->pan);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenClass !== null) {
            $xfer += $output->writeFieldBegin('tokenClass', TType::I16, 10);
            $xfer += $output->writeI16($this->tokenClass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->subclass !== null) {
            $xfer += $output->writeFieldBegin('subclass', TType::I16, 11);
            $xfer += $output->writeI16($this->subclass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->control !== null) {
            $xfer += $output->writeFieldBegin('control', TType::I64, 12);
            $xfer += $output->writeI64($this->control);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->mfrcode !== null) {
            $xfer += $output->writeFieldBegin('mfrcode', TType::I16, 13);
            $xfer += $output->writeI16($this->mfrcode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->description !== null) {
            $xfer += $output->writeFieldBegin('description', TType::STRING, 20);
            $xfer += $output->writeString($this->description);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenDec !== null) {
            $xfer += $output->writeFieldBegin('tokenDec', TType::STRING, 30);
            $xfer += $output->writeString($this->tokenDec);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenHex !== null) {
            $xfer += $output->writeFieldBegin('tokenHex', TType::STRING, 31);
            $xfer += $output->writeString($this->tokenHex);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
