<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MeterConfigIn
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'drn',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'ea',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        3 => array(
            'var' => 'tct',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        10 => array(
            'var' => 'sgc',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        11 => array(
            'var' => 'krn',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        12 => array(
            'var' => 'ti',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        20 => array(
            'var' => 'newConfig',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\MeterConfigAmendment',
        ),
        21 => array(
            'var' => 'allowKrnUpdate',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        30 => array(
            'var' => 'ken',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        31 => array(
            'var' => 'doe',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        32 => array(
            'var' => 'allow3Kct',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        33 => array(
            'var' => 'allowKenUpdate',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var string
     */
    public $drn = null;
    /**
     * @var int
     */
    public $ea = null;
    /**
     * @var int
     */
    public $tct = null;
    /**
     * @var int
     */
    public $sgc = null;
    /**
     * @var int
     */
    public $krn = null;
    /**
     * @var int
     */
    public $ti = null;
    /**
     * @var \Prism\PrismToken1\MeterConfigAmendment
     */
    public $newConfig = null;
    /**
     * @var bool
     */
    public $allowKrnUpdate = true;
    /**
     * @var int
     */
    public $ken = null;
    /**
     * @var string
     */
    public $doe = "0000";
    /**
     * @var bool
     */
    public $allow3Kct = false;
    /**
     * @var bool
     */
    public $allowKenUpdate = true;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['drn'])) {
                $this->drn = $vals['drn'];
            }
            if (isset($vals['ea'])) {
                $this->ea = $vals['ea'];
            }
            if (isset($vals['tct'])) {
                $this->tct = $vals['tct'];
            }
            if (isset($vals['sgc'])) {
                $this->sgc = $vals['sgc'];
            }
            if (isset($vals['krn'])) {
                $this->krn = $vals['krn'];
            }
            if (isset($vals['ti'])) {
                $this->ti = $vals['ti'];
            }
            if (isset($vals['newConfig'])) {
                $this->newConfig = $vals['newConfig'];
            }
            if (isset($vals['allowKrnUpdate'])) {
                $this->allowKrnUpdate = $vals['allowKrnUpdate'];
            }
            if (isset($vals['ken'])) {
                $this->ken = $vals['ken'];
            }
            if (isset($vals['doe'])) {
                $this->doe = $vals['doe'];
            }
            if (isset($vals['allow3Kct'])) {
                $this->allow3Kct = $vals['allow3Kct'];
            }
            if (isset($vals['allowKenUpdate'])) {
                $this->allowKenUpdate = $vals['allowKenUpdate'];
            }
        }
    }

    public function getName()
    {
        return 'MeterConfigIn';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->drn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->ea);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->tct);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->sgc);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->krn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->ti);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 20:
                    if ($ftype == TType::STRUCT) {
                        $this->newConfig = new \Prism\PrismToken1\MeterConfigAmendment();
                        $xfer += $this->newConfig->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 21:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->allowKrnUpdate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 30:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->ken);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 31:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->doe);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 32:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->allow3Kct);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 33:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->allowKenUpdate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MeterConfigIn');
        if ($this->drn !== null) {
            $xfer += $output->writeFieldBegin('drn', TType::STRING, 1);
            $xfer += $output->writeString($this->drn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ea !== null) {
            $xfer += $output->writeFieldBegin('ea', TType::I16, 2);
            $xfer += $output->writeI16($this->ea);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tct !== null) {
            $xfer += $output->writeFieldBegin('tct', TType::I16, 3);
            $xfer += $output->writeI16($this->tct);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sgc !== null) {
            $xfer += $output->writeFieldBegin('sgc', TType::I32, 10);
            $xfer += $output->writeI32($this->sgc);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->krn !== null) {
            $xfer += $output->writeFieldBegin('krn', TType::I16, 11);
            $xfer += $output->writeI16($this->krn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ti !== null) {
            $xfer += $output->writeFieldBegin('ti', TType::I16, 12);
            $xfer += $output->writeI16($this->ti);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->newConfig !== null) {
            if (!is_object($this->newConfig)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('newConfig', TType::STRUCT, 20);
            $xfer += $this->newConfig->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->allowKrnUpdate !== null) {
            $xfer += $output->writeFieldBegin('allowKrnUpdate', TType::BOOL, 21);
            $xfer += $output->writeBool($this->allowKrnUpdate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ken !== null) {
            $xfer += $output->writeFieldBegin('ken', TType::I16, 30);
            $xfer += $output->writeI16($this->ken);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->doe !== null) {
            $xfer += $output->writeFieldBegin('doe', TType::STRING, 31);
            $xfer += $output->writeString($this->doe);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->allow3Kct !== null) {
            $xfer += $output->writeFieldBegin('allow3Kct', TType::BOOL, 32);
            $xfer += $output->writeBool($this->allow3Kct);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->allowKenUpdate !== null) {
            $xfer += $output->writeFieldBegin('allowKenUpdate', TType::BOOL, 33);
            $xfer += $output->writeBool($this->allowKenUpdate);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
