<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SessionOptions
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'version',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        10 => array(
            'var' => 'culture',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $version = "1.1";
    /**
     * @var string
     */
    public $culture = "en";

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['version'])) {
                $this->version = $vals['version'];
            }
            if (isset($vals['culture'])) {
                $this->culture = $vals['culture'];
            }
        }
    }

    public function getName()
    {
        return 'SessionOptions';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->version);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->culture);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SessionOptions');
        if ($this->version !== null) {
            $xfer += $output->writeFieldBegin('version', TType::STRING, 1);
            $xfer += $output->writeString($this->version);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->culture !== null) {
            $xfer += $output->writeFieldBegin('culture', TType::STRING, 10);
            $xfer += $output->writeString($this->culture);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
