<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface TokenApiIf
{
    /**
     * @param int $sleepMs
     * @param string $echo
     * @return string
     * @throws \Prism\PrismToken1\ApiException
     */
    public function ping($sleepMs, $echo);
    /**
     * @param string $messageId
     * @param string $realm
     * @param string $username
     * @param string $password
     * @param \Prism\PrismToken1\SessionOptions $sessionOpts
     * @return \Prism\PrismToken1\SignInResult
     * @throws \Prism\PrismToken1\ApiException
     */
    public function signInWithPassword($messageId, $realm, $username, $password, \Prism\PrismToken1\SessionOptions $sessionOpts);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @return \Prism\PrismToken1\NodeStatus[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function getStatus($messageId, $accessToken);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param string $idRecord
     * @return \Prism\PrismToken1\MeterConfigIn
     * @throws \Prism\PrismToken1\ApiException
     */
    public function parseIdRecord($messageId, $accessToken, $idRecord);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param string $licenseText
     * @return bool
     * @throws \Prism\PrismToken1\ApiException
     */
    public function loadTransactionLicense($messageId, $accessToken, $licenseText);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @param int $subclass
     * @param double $transferAmount
     * @param int $tokenTime
     * @param int $flags
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueCreditToken($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig, $subclass, $transferAmount, $tokenTime, $flags);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param int $subclass
     * @param int $control
     * @param int $mfrcode
     * @return \Prism\PrismToken1\MeterTestToken
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueMeterTestToken($messageId, $accessToken, $subclass, $control, $mfrcode);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @param int $subclass
     * @param double $transferAmount
     * @param int $tokenTime
     * @param int $flags
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueMseToken($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig, $subclass, $transferAmount, $tokenTime, $flags);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @param bool $isFlag
     * @param int $index
     * @param int $value
     * @param int $tokenTime
     * @param int $flags
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueSetControlToken($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig, $isFlag, $index, $value, $tokenTime, $flags);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @param \Prism\PrismToken1\MeterConfigAmendment $newConfig
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueKeyChangeTokens($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig, \Prism\PrismToken1\MeterConfigAmendment $newConfig);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @param string $tokenDec
     * @return \Prism\PrismToken1\VerifyResult
     * @throws \Prism\PrismToken1\ApiException
     */
    public function verifyToken($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig, $tokenDec);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param \Prism\PrismToken1\MeterConfigIn $meterConfig
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function issueDitkChangeTokens($messageId, $accessToken, \Prism\PrismToken1\MeterConfigIn $meterConfig);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param string $reqMessageId
     * @return \Prism\PrismToken1\Token[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function fetchTokenResult($messageId, $accessToken, $reqMessageId);
    /**
     * @param string $messageId
     * @param string $accessToken
     * @param string $panPattern
     * @return string[]
     * @throws \Prism\PrismToken1\ApiException
     */
    public function ctsResetTidList($messageId, $accessToken, $panPattern);
}
