<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TokenApi_signInWithPassword_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'messageId',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'realm',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'username',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'password',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'sessionOpts',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\SessionOptions',
        ),
    );

    /**
     * @var string
     */
    public $messageId = null;
    /**
     * @var string
     */
    public $realm = null;
    /**
     * @var string
     */
    public $username = null;
    /**
     * @var string
     */
    public $password = null;
    /**
     * @var \Prism\PrismToken1\SessionOptions
     */
    public $sessionOpts = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['messageId'])) {
                $this->messageId = $vals['messageId'];
            }
            if (isset($vals['realm'])) {
                $this->realm = $vals['realm'];
            }
            if (isset($vals['username'])) {
                $this->username = $vals['username'];
            }
            if (isset($vals['password'])) {
                $this->password = $vals['password'];
            }
            if (isset($vals['sessionOpts'])) {
                $this->sessionOpts = $vals['sessionOpts'];
            }
        }
    }

    public function getName()
    {
        return 'TokenApi_signInWithPassword_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->messageId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->realm);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->username);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->password);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRUCT) {
                        $this->sessionOpts = new \Prism\PrismToken1\SessionOptions();
                        $xfer += $this->sessionOpts->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TokenApi_signInWithPassword_args');
        if ($this->messageId !== null) {
            $xfer += $output->writeFieldBegin('messageId', TType::STRING, 1);
            $xfer += $output->writeString($this->messageId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->realm !== null) {
            $xfer += $output->writeFieldBegin('realm', TType::STRING, 2);
            $xfer += $output->writeString($this->realm);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->username !== null) {
            $xfer += $output->writeFieldBegin('username', TType::STRING, 3);
            $xfer += $output->writeString($this->username);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->password !== null) {
            $xfer += $output->writeFieldBegin('password', TType::STRING, 4);
            $xfer += $output->writeString($this->password);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sessionOpts !== null) {
            if (!is_object($this->sessionOpts)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('sessionOpts', TType::STRUCT, 5);
            $xfer += $this->sessionOpts->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
