<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TokenApi_issueMseToken_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'messageId',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'accessToken',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'meterConfig',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\MeterConfigIn',
        ),
        4 => array(
            'var' => 'subclass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        5 => array(
            'var' => 'transferAmount',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ),
        6 => array(
            'var' => 'tokenTime',
            'isRequired' => true,
            'type' => TType::I64,
        ),
        7 => array(
            'var' => 'flags',
            'isRequired' => true,
            'type' => TType::I64,
        ),
    );

    /**
     * @var string
     */
    public $messageId = null;
    /**
     * @var string
     */
    public $accessToken = null;
    /**
     * @var \Prism\PrismToken1\MeterConfigIn
     */
    public $meterConfig = null;
    /**
     * @var int
     */
    public $subclass = null;
    /**
     * @var double
     */
    public $transferAmount = null;
    /**
     * @var int
     */
    public $tokenTime = null;
    /**
     * @var int
     */
    public $flags = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['messageId'])) {
                $this->messageId = $vals['messageId'];
            }
            if (isset($vals['accessToken'])) {
                $this->accessToken = $vals['accessToken'];
            }
            if (isset($vals['meterConfig'])) {
                $this->meterConfig = $vals['meterConfig'];
            }
            if (isset($vals['subclass'])) {
                $this->subclass = $vals['subclass'];
            }
            if (isset($vals['transferAmount'])) {
                $this->transferAmount = $vals['transferAmount'];
            }
            if (isset($vals['tokenTime'])) {
                $this->tokenTime = $vals['tokenTime'];
            }
            if (isset($vals['flags'])) {
                $this->flags = $vals['flags'];
            }
        }
    }

    public function getName()
    {
        return 'TokenApi_issueMseToken_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->messageId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->accessToken);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->meterConfig = new \Prism\PrismToken1\MeterConfigIn();
                        $xfer += $this->meterConfig->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->subclass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->transferAmount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->tokenTime);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->flags);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TokenApi_issueMseToken_args');
        if ($this->messageId !== null) {
            $xfer += $output->writeFieldBegin('messageId', TType::STRING, 1);
            $xfer += $output->writeString($this->messageId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->accessToken !== null) {
            $xfer += $output->writeFieldBegin('accessToken', TType::STRING, 2);
            $xfer += $output->writeString($this->accessToken);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->meterConfig !== null) {
            if (!is_object($this->meterConfig)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('meterConfig', TType::STRUCT, 3);
            $xfer += $this->meterConfig->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->subclass !== null) {
            $xfer += $output->writeFieldBegin('subclass', TType::I16, 4);
            $xfer += $output->writeI16($this->subclass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->transferAmount !== null) {
            $xfer += $output->writeFieldBegin('transferAmount', TType::DOUBLE, 5);
            $xfer += $output->writeDouble($this->transferAmount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenTime !== null) {
            $xfer += $output->writeFieldBegin('tokenTime', TType::I64, 6);
            $xfer += $output->writeI64($this->tokenTime);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->flags !== null) {
            $xfer += $output->writeFieldBegin('flags', TType::I64, 7);
            $xfer += $output->writeI64($this->flags);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
