<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TokenApi_issueMeterTestToken_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'messageId',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'accessToken',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'subclass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        4 => array(
            'var' => 'control',
            'isRequired' => true,
            'type' => TType::I64,
        ),
        5 => array(
            'var' => 'mfrcode',
            'isRequired' => true,
            'type' => TType::I16,
        ),
    );

    /**
     * @var string
     */
    public $messageId = null;
    /**
     * @var string
     */
    public $accessToken = null;
    /**
     * @var int
     */
    public $subclass = null;
    /**
     * @var int
     */
    public $control = null;
    /**
     * @var int
     */
    public $mfrcode = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['messageId'])) {
                $this->messageId = $vals['messageId'];
            }
            if (isset($vals['accessToken'])) {
                $this->accessToken = $vals['accessToken'];
            }
            if (isset($vals['subclass'])) {
                $this->subclass = $vals['subclass'];
            }
            if (isset($vals['control'])) {
                $this->control = $vals['control'];
            }
            if (isset($vals['mfrcode'])) {
                $this->mfrcode = $vals['mfrcode'];
            }
        }
    }

    public function getName()
    {
        return 'TokenApi_issueMeterTestToken_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->messageId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->accessToken);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->subclass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->control);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->mfrcode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TokenApi_issueMeterTestToken_args');
        if ($this->messageId !== null) {
            $xfer += $output->writeFieldBegin('messageId', TType::STRING, 1);
            $xfer += $output->writeString($this->messageId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->accessToken !== null) {
            $xfer += $output->writeFieldBegin('accessToken', TType::STRING, 2);
            $xfer += $output->writeString($this->accessToken);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->subclass !== null) {
            $xfer += $output->writeFieldBegin('subclass', TType::I16, 3);
            $xfer += $output->writeI16($this->subclass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->control !== null) {
            $xfer += $output->writeFieldBegin('control', TType::I64, 4);
            $xfer += $output->writeI64($this->control);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->mfrcode !== null) {
            $xfer += $output->writeFieldBegin('mfrcode', TType::I16, 5);
            $xfer += $output->writeI16($this->mfrcode);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
