<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class TokenIssueFlags
{
    const EXTERNAL_CLOCK = 1;

    const TID_ADJUST_BDT = 2;

    const SPECIAL_RESERVED = 4;

    static public $__names = array(
        1 => 'EXTERNAL_CLOCK',
        2 => 'TID_ADJUST_BDT',
        4 => 'SPECIAL_RESERVED',
    );
}

