<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Token
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'drn',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'pan',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'ea',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        4 => array(
            'var' => 'tct',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        5 => array(
            'var' => 'sgc',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        6 => array(
            'var' => 'krn',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        7 => array(
            'var' => 'ti',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        10 => array(
            'var' => 'tokenClass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        11 => array(
            'var' => 'subclass',
            'isRequired' => true,
            'type' => TType::I16,
        ),
        12 => array(
            'var' => 'tid',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        13 => array(
            'var' => 'transferAmount',
            'isRequired' => true,
            'type' => TType::DOUBLE,
        ),
        14 => array(
            'var' => 'isReservedTid',
            'isRequired' => true,
            'type' => TType::BOOL,
        ),
        15 => array(
            'var' => 'newConfig',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\MeterConfigAdvice',
        ),
        20 => array(
            'var' => 'description',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        21 => array(
            'var' => 'stsUnitName',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        22 => array(
            'var' => 'scaledAmount',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        23 => array(
            'var' => 'scaledUnitName',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        30 => array(
            'var' => 'tokenDec',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        31 => array(
            'var' => 'tokenHex',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        40 => array(
            'var' => 'idSm',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        41 => array(
            'var' => 'vkKcv',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $drn = null;
    /**
     * @var string
     */
    public $pan = null;
    /**
     * @var int
     */
    public $ea = null;
    /**
     * @var int
     */
    public $tct = null;
    /**
     * @var int
     */
    public $sgc = null;
    /**
     * @var int
     */
    public $krn = null;
    /**
     * @var int
     */
    public $ti = null;
    /**
     * @var int
     */
    public $tokenClass = null;
    /**
     * @var int
     */
    public $subclass = null;
    /**
     * @var int
     */
    public $tid = null;
    /**
     * @var double
     */
    public $transferAmount = null;
    /**
     * @var bool
     */
    public $isReservedTid = null;
    /**
     * @var \Prism\PrismToken1\MeterConfigAdvice
     */
    public $newConfig = null;
    /**
     * @var string
     */
    public $description = null;
    /**
     * @var string
     */
    public $stsUnitName = null;
    /**
     * @var string
     */
    public $scaledAmount = null;
    /**
     * @var string
     */
    public $scaledUnitName = null;
    /**
     * @var string
     */
    public $tokenDec = null;
    /**
     * @var string
     */
    public $tokenHex = null;
    /**
     * @var string
     */
    public $idSm = null;
    /**
     * @var string
     */
    public $vkKcv = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['drn'])) {
                $this->drn = $vals['drn'];
            }
            if (isset($vals['pan'])) {
                $this->pan = $vals['pan'];
            }
            if (isset($vals['ea'])) {
                $this->ea = $vals['ea'];
            }
            if (isset($vals['tct'])) {
                $this->tct = $vals['tct'];
            }
            if (isset($vals['sgc'])) {
                $this->sgc = $vals['sgc'];
            }
            if (isset($vals['krn'])) {
                $this->krn = $vals['krn'];
            }
            if (isset($vals['ti'])) {
                $this->ti = $vals['ti'];
            }
            if (isset($vals['tokenClass'])) {
                $this->tokenClass = $vals['tokenClass'];
            }
            if (isset($vals['subclass'])) {
                $this->subclass = $vals['subclass'];
            }
            if (isset($vals['tid'])) {
                $this->tid = $vals['tid'];
            }
            if (isset($vals['transferAmount'])) {
                $this->transferAmount = $vals['transferAmount'];
            }
            if (isset($vals['isReservedTid'])) {
                $this->isReservedTid = $vals['isReservedTid'];
            }
            if (isset($vals['newConfig'])) {
                $this->newConfig = $vals['newConfig'];
            }
            if (isset($vals['description'])) {
                $this->description = $vals['description'];
            }
            if (isset($vals['stsUnitName'])) {
                $this->stsUnitName = $vals['stsUnitName'];
            }
            if (isset($vals['scaledAmount'])) {
                $this->scaledAmount = $vals['scaledAmount'];
            }
            if (isset($vals['scaledUnitName'])) {
                $this->scaledUnitName = $vals['scaledUnitName'];
            }
            if (isset($vals['tokenDec'])) {
                $this->tokenDec = $vals['tokenDec'];
            }
            if (isset($vals['tokenHex'])) {
                $this->tokenHex = $vals['tokenHex'];
            }
            if (isset($vals['idSm'])) {
                $this->idSm = $vals['idSm'];
            }
            if (isset($vals['vkKcv'])) {
                $this->vkKcv = $vals['vkKcv'];
            }
        }
    }

    public function getName()
    {
        return 'Token';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->drn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->pan);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->ea);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->tct);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->sgc);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->krn);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->ti);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->tokenClass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->subclass);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->tid);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->transferAmount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 14:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->isReservedTid);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 15:
                    if ($ftype == TType::STRUCT) {
                        $this->newConfig = new \Prism\PrismToken1\MeterConfigAdvice();
                        $xfer += $this->newConfig->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 20:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->description);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 21:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->stsUnitName);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 22:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->scaledAmount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 23:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->scaledUnitName);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 30:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tokenDec);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 31:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tokenHex);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 40:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->idSm);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 41:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->vkKcv);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Token');
        if ($this->drn !== null) {
            $xfer += $output->writeFieldBegin('drn', TType::STRING, 1);
            $xfer += $output->writeString($this->drn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->pan !== null) {
            $xfer += $output->writeFieldBegin('pan', TType::STRING, 2);
            $xfer += $output->writeString($this->pan);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ea !== null) {
            $xfer += $output->writeFieldBegin('ea', TType::I16, 3);
            $xfer += $output->writeI16($this->ea);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tct !== null) {
            $xfer += $output->writeFieldBegin('tct', TType::I16, 4);
            $xfer += $output->writeI16($this->tct);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sgc !== null) {
            $xfer += $output->writeFieldBegin('sgc', TType::I32, 5);
            $xfer += $output->writeI32($this->sgc);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->krn !== null) {
            $xfer += $output->writeFieldBegin('krn', TType::I16, 6);
            $xfer += $output->writeI16($this->krn);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ti !== null) {
            $xfer += $output->writeFieldBegin('ti', TType::I16, 7);
            $xfer += $output->writeI16($this->ti);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenClass !== null) {
            $xfer += $output->writeFieldBegin('tokenClass', TType::I16, 10);
            $xfer += $output->writeI16($this->tokenClass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->subclass !== null) {
            $xfer += $output->writeFieldBegin('subclass', TType::I16, 11);
            $xfer += $output->writeI16($this->subclass);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tid !== null) {
            $xfer += $output->writeFieldBegin('tid', TType::I32, 12);
            $xfer += $output->writeI32($this->tid);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->transferAmount !== null) {
            $xfer += $output->writeFieldBegin('transferAmount', TType::DOUBLE, 13);
            $xfer += $output->writeDouble($this->transferAmount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->isReservedTid !== null) {
            $xfer += $output->writeFieldBegin('isReservedTid', TType::BOOL, 14);
            $xfer += $output->writeBool($this->isReservedTid);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->newConfig !== null) {
            if (!is_object($this->newConfig)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('newConfig', TType::STRUCT, 15);
            $xfer += $this->newConfig->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->description !== null) {
            $xfer += $output->writeFieldBegin('description', TType::STRING, 20);
            $xfer += $output->writeString($this->description);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->stsUnitName !== null) {
            $xfer += $output->writeFieldBegin('stsUnitName', TType::STRING, 21);
            $xfer += $output->writeString($this->stsUnitName);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->scaledAmount !== null) {
            $xfer += $output->writeFieldBegin('scaledAmount', TType::STRING, 22);
            $xfer += $output->writeString($this->scaledAmount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->scaledUnitName !== null) {
            $xfer += $output->writeFieldBegin('scaledUnitName', TType::STRING, 23);
            $xfer += $output->writeString($this->scaledUnitName);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenDec !== null) {
            $xfer += $output->writeFieldBegin('tokenDec', TType::STRING, 30);
            $xfer += $output->writeString($this->tokenDec);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tokenHex !== null) {
            $xfer += $output->writeFieldBegin('tokenHex', TType::STRING, 31);
            $xfer += $output->writeString($this->tokenHex);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->idSm !== null) {
            $xfer += $output->writeFieldBegin('idSm', TType::STRING, 40);
            $xfer += $output->writeString($this->idSm);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->vkKcv !== null) {
            $xfer += $output->writeFieldBegin('vkKcv', TType::STRING, 41);
            $xfer += $output->writeString($this->vkKcv);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
