<?php
namespace Prism\PrismToken1;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class VerifyResult
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'validationResult',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'token',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\Token',
        ),
        3 => array(
            'var' => 'meterTestToken',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Prism\PrismToken1\MeterTestToken',
        ),
    );

    /**
     * @var string
     */
    public $validationResult = null;
    /**
     * @var \Prism\PrismToken1\Token
     */
    public $token = null;
    /**
     * @var \Prism\PrismToken1\MeterTestToken
     */
    public $meterTestToken = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['validationResult'])) {
                $this->validationResult = $vals['validationResult'];
            }
            if (isset($vals['token'])) {
                $this->token = $vals['token'];
            }
            if (isset($vals['meterTestToken'])) {
                $this->meterTestToken = $vals['meterTestToken'];
            }
        }
    }

    public function getName()
    {
        return 'VerifyResult';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->validationResult);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->token = new \Prism\PrismToken1\Token();
                        $xfer += $this->token->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->meterTestToken = new \Prism\PrismToken1\MeterTestToken();
                        $xfer += $this->meterTestToken->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('VerifyResult');
        if ($this->validationResult !== null) {
            $xfer += $output->writeFieldBegin('validationResult', TType::STRING, 1);
            $xfer += $output->writeString($this->validationResult);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->token !== null) {
            if (!is_object($this->token)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('token', TType::STRUCT, 2);
            $xfer += $this->token->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->meterTestToken !== null) {
            if (!is_object($this->meterTestToken)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('meterTestToken', TType::STRUCT, 3);
            $xfer += $this->meterTestToken->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
